version: "3.1"
networks:
  jenkins-moka:
services:
  jenkins-moka:
    build: jenkins
    networks:
      - jenkins-moka
    ports:
      - "3001:8080"
      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home
  # jenkins-nginx:
  #   build: nginx
  #   networks:
  #     - jenkins-moka
  #   depends_on:
  #     - jenkins-moka
  #   ports:
  #     - "3001:3001"

volumes:
  data:
